In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from collections import Counter

In [2]:
data = pd.read_csv("diabetes75pc_100_times.csv")

In [3]:
data["Outcome"].value_counts()

0    50500
1    27068
Name: Outcome, dtype: int64

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77568 entries, 0 to 77567
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               77568 non-null  int64  
 1   Glucose                   77568 non-null  int64  
 2   BloodPressure             77568 non-null  int64  
 3   SkinThickness             77568 non-null  int64  
 4   Insulin                   77568 non-null  int64  
 5   BMI                       77568 non-null  float64
 6   DiabetesPedigreeFunction  77568 non-null  float64
 7   Age                       77568 non-null  int64  
 8   Outcome                   77568 non-null  int64  
dtypes: float64(2), int64(7)
memory usage: 5.3 MB


In [5]:
X = data.drop("Outcome", axis=1)
y = data["Outcome"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [7]:
X_train.shape

(62054, 8)

In [8]:
columns = ["Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age"]

In [9]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(X_train)

In [10]:
X_train = pd.DataFrame(scaled_data, columns=columns)

In [11]:
X_train

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin  \
0         0.338571  0.092918       0.147859       0.154129  0.278164   
1        -0.253827 -1.082823       0.147859       0.717886 -0.691528   
2         0.338571  0.635567       0.665322       0.342048  1.775991   
3        -0.846226 -3.765922       0.251352      -0.033790 -0.492395   
4        -0.253827 -1.806355       0.665322       0.467328 -0.691528   
...            ...       ...            ...            ...       ...   
62049    -1.142425  0.876745       1.079292       1.594842 -0.691528   
62050    -1.142425 -0.510026       0.044366       1.031085  0.589850   
62051     0.634771 -0.962234      -0.369604       0.717886  0.399375   
62052     0.634771  2.173074       1.182785      -1.286584 -0.691528   
62053    -0.550026 -0.510026      -0.369604      -0.660187  1.715385   

            BMI  DiabetesPedigreeFunction       Age  
0     -0.617184                 -0.696638 -0.276543  
1      0.591661                 -0.638609 -0.446725  
2      0.067504                 -0.087333  2.106009  
3     -0.470031                 -0.522551 -1.042363  
4      0.369107                 -0.696638  1.084916  
...         ...                       ...       ...  
62049  1.231353                 -0.290435 -1.042363  
62050  0.965017                  0.376899 -0.957272  
62051 -0.136808                 -1.160870  1.084916  
62052  0.319245                 -0.609594  2.786739  
62053 -0.828793                  1.218320 -0.957272  

[62054 rows x 8 columns]

In [12]:
scaled_test = scaler.transform(X_test)
X_test = pd.DataFrame(scaled_test, columns=columns)

In [13]:
X_test

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin  \
0        -1.142425 -0.479879      -0.473097       0.279409 -0.691528   
1        -0.253827  1.419394      -0.266111       1.031085  1.256513   
2        -0.846226 -0.962234       0.044366       0.655247 -0.691528   
3        -0.550026  0.243654      -0.576589       0.216769  1.689411   
4        -0.253827 -1.384294       0.044366      -1.286584 -0.691528   
...            ...       ...            ...            ...       ...   
15509     0.930970  0.575273       1.079292       0.216769  3.464293   
15510     1.523368  0.997333       0.872307       0.467328  0.650456   
15511     0.634771 -0.087965       1.389770      -1.286584 -0.691528   
15512     1.227169  1.690719       1.079292       0.843166  1.905860   
15513    -0.550026  0.123065      -1.197545       0.028850  2.208889   

            BMI  DiabetesPedigreeFunction       Age  
0     -0.701098                 -1.015797 -0.872181  
1      0.167228                 -0.377478 -0.276543  
2     -0.122214                 -0.493536 -0.872181  
3     -0.423818                  3.481451 -0.701999  
4     -0.073569                 -0.580580  0.489278  
...         ...                       ...       ...  
15509 -0.286394                 -1.044812  0.829642  
15510  0.434779                  2.204813  0.744551  
15511 -0.409224                 -0.957768 -0.276543  
15512  0.283977                 -0.029304  2.106009  
15513  0.209793                 -0.899739 -0.957272  

[15514 rows x 8 columns]

In [14]:
tree = DecisionTreeClassifier(random_state=10)

In [15]:
tree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=10)

In [16]:
pred = tree.predict(X_test)

In [17]:
tree.score(X_train, y_train)

1.0

In [18]:
accuracy_score(y_test, pred)

0.9998710841820291

In [19]:
confusion_matrix(y_test, pred)

array([[10143,     0],
       [    2,  5369]])

In [20]:
forest = RandomForestClassifier(random_state=10)

In [21]:
forest.fit(X_train, y_train)

RandomForestClassifier(random_state=10)

In [22]:
pred_f = forest.predict(X_test)

In [23]:
accuracy_score(y_test, pred_f)

1.0

In [24]:
confusion_matrix(y_test, pred_f)

array([[10143,     0],
       [    0,  5371]])

In [ ]:
svm_clf = SVC(random_state=10)
svm_clf.fit(X_train, y_train)

In [ ]:
pred_s = svm_clf.predict(X_test)

In [ ]:
accuracy_score(y_test, pred_s)

In [ ]:
confusion_matrix(y_test, pred_s)

In [ ]:
# the numbers before smote
num_before = dict(Counter(y))

#perform smoting

# define pipeline
over = SMOTE(sampling_strategy=0.8)
under = RandomUnderSampler(sampling_strategy=0.8)
steps = [('o', over), ('u', under)]
pipeline = Pipeline(steps=steps)

# transform the dataset
X_smote, y_smote = pipeline.fit_resample(X, y)


#the numbers after smote
num_after =dict(Counter(y_smote))

In [ ]:
num_before

In [ ]:
num_after

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [ ]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(X_train)

In [ ]:
X_train = pd.DataFrame(scaled_data, columns=columns)

In [ ]:
scaled_test = scaler.transform(X_test)
X_test = pd.DataFrame(scaled_test, columns=columns)

In [ ]:
forest_s = RandomForestClassifier(random_state=5)

In [ ]:
forest_s.fit(X_train, y_train)
pred_s = forest_s.predict(X_test)

In [ ]:
accuracy_score(y_test, pred_s)

In [ ]:
confusion_matrix(y_test, pred_s)

### Neural Network

In [25]:
import pandas
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [32]:
model = Sequential([
    Dense(8, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [33]:
model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])

In [34]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
1940/1940 [==============================] - 3s 1ms/step - loss: 0.5120 - accuracy: 0.7405
Epoch 2/100
1940/1940 [==============================] - 2s 1ms/step - loss: 0.4163 - accuracy: 0.8020
Epoch 3/100
1940/1940 [==============================] - 2s 1ms/step - loss: 0.3926 - accuracy: 0.8090
Epoch 4/100
1940/1940 [==============================] - 2s 1ms/step - loss: 0.3586 - accuracy: 0.8268
Epoch 5/100
1940/1940 [==============================] - 2s 1ms/step - loss: 0.3437 - accuracy: 0.8346
Epoch 6/100
1940/1940 [==============================] - 2s 1ms/step - loss: 0.3266 - accuracy: 0.8462
Epoch 7/100
1940/1940 [==============================] - 2s 1ms/step - loss: 0.3142 - accuracy: 0.8575
Epoch 8/100
1940/1940 [==============================] - 2s 1ms/step - loss: 0.3055 - accuracy: 0.8626
Epoch 9/100
1940/1940 [==============================] - 2s 1ms/step - loss: 0.2926 - accuracy: 0.8687
Epoch 10/100
1940/1940 [==============================] - 3s 1ms/step - l

1940/1940 [==============================] - 3s 1ms/step - loss: 0.1079 - accuracy: 0.9595
Epoch 80/100
1940/1940 [==============================] - 3s 1ms/step - loss: 0.1059 - accuracy: 0.9605
Epoch 81/100
1940/1940 [==============================] - 3s 1ms/step - loss: 0.1068 - accuracy: 0.9612
Epoch 82/100
1940/1940 [==============================] - 3s 2ms/step - loss: 0.1068 - accuracy: 0.9612
Epoch 83/100
1940/1940 [==============================] - 3s 2ms/step - loss: 0.1058 - accuracy: 0.9615
Epoch 84/100
1940/1940 [==============================] - 3s 2ms/step - loss: 0.1041 - accuracy: 0.9636
Epoch 85/100
1940/1940 [==============================] - 3s 1ms/step - loss: 0.0998 - accuracy: 0.9651
Epoch 86/100
1940/1940 [==============================] - 2s 1ms/step - loss: 0.0997 - accuracy: 0.9641
Epoch 87/100
1940/1940 [==============================] - 3s 1ms/step - loss: 0.0996 - accuracy: 0.9644
Epoch 88/100
1940/1940 [==============================] - 3s 1ms/step - loss:

In [35]:
p = model.predict(X_test)

In [36]:
pred = np.round(p)

In [37]:
accuracy_score(y_test, pred)

0.9708650251385845

In [39]:
confusion_matrix(y_test, pred)

array([[9943,  200],
       [ 252, 5119]])

In [38]:
model.save("NN.h5")

In [40]:
model.save_weights("NN_Weight.h5")

### Logistic Regression

In [43]:
from sklearn.linear_model import LogisticRegression

In [44]:
log_reg = LogisticRegression(random_state=10)

In [ ]:
log_reg.fit(X_train, y_train)
pred = log_reg.predict(X_test)

In [ ]:
accuracy_score(y_test, pred)

### Ensemble All

In [41]:
from sklearn.ensemble import VotingClassifier

In [45]:
voting_clf = VotingClassifier(
estimators=[('lr', log_reg), ('rf', forest),('dt', tree)], voting='hard')
voting_clf.fit(X_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=10)),
                             ('rf', RandomForestClassifier(random_state=10)),
                             ('dt', DecisionTreeClassifier(random_state=10))])

In [46]:
pred = voting_clf.predict(X_test)

In [47]:
accuracy_score(y_test, pred)

0.9998710841820291

In [48]:
confusion_matrix(y_test, pred)

array([[10143,     0],
       [    2,  5369]])